name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        files: ./bin/release/netcoreapp3.1/publish/*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build -c release
      run: dotnet build --no-restore
    - name: Release
      run: dotnet publish -c release
